### ISSUE TITLE
Explain the need for "__do_not_execute" as parent task in EvaluatedValue

### ISSUE THREAD

**Issue by tbrandtner** [Renneke/xyzflow#12]
In EvalutedValue class the self.input_named is set to a dictionary with "__do_not_execute": parent_task. Later this will help to track the source of the evaluated value, with all its dependency tree. That's great - but I would add a comment to that line in the source code - otherwise it is difficult to understand why you store the parent task in "__do_not_execute".

**Comment by Renneke** [comment]
The evaluated value class could be removed because it is not needed as we discussed. So This issue is obsolete.
