### ISSUE TITLE
Task __call__ should return the value, not the EvaluatedValue object

### ISSUE THREAD

**Issue by tbrandtner** [Renneke/xyzflow#15]
If a task contains ifs and loops, the code will contain several task evaluations (like mytask())
Currently this call returns an EvaluatedValue object. In an if or loop one need to query the real result with mytask().result. I think it will be more intuitive, if mytask() returns the result directly.

In subsequent statements, the user should use the task mytask again - instead of the evaluated value: On the one hand this will keep the complete dependency graph - but ask mytask has been evaluated (has_run == True), its result will be used anyway.

Very simple example:
Task v ...

Today:
while ( v().result < 15 ):
  v = v + 1
...
x = v().result

Improved?
while ( v() < 15 ):
  v = v + 1
...
x = v()

And if you are not sure whether it would make sense to use EvaluatedValue object in some circumstances, you can still offer a method like mytask.evaluate() or so, which returns the object instead of the value (like today __call__).

**Comment by Renneke** [comment]
Has been implemented
